DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS ACL_ENTRY;
DROP TABLE IF EXISTS ACL_OBJECT_IDENTITY;
DROP TABLE IF EXISTS ACL_CLASS;
DROP TABLE IF EXISTS ACL_SID;
DROP TABLE IF EXISTS ADMIN_POST;
DROP TABLE IF EXISTS PERSONAL_POST;
DROP TABLE IF EXISTS PUBLIC_POST;

CREATE TABLE CONTACT (
    ID INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , VERSION INT NOT NULL DEFAULT 0
    , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (ID)
);

CREATE TABLE ACL_SID (
    ID BIGINT NOT NULL AUTO_INCREMENT
	, PRINCIPAL BOOLEAN NOT NULL
	, SID VARCHAR(100) NOT NULL
	, UNIQUE UNIQUE_UK_1 (SID,PRINCIPAL)
	, PRIMARY KEY (ID)
);

CREATE TABLE ACL_CLASS(
    ID BIGINT NOT NULL AUTO_INCREMENT
    , CLASS VARCHAR NOT NULL
    , UNIQUE UNIQUE_UK_2 (CLASS)
    , PRIMARY KEY (ID)
);

CREATE TABLE ACL_OBJECT_IDENTITY(
    ID BIGINT NOT NULL AUTO_INCREMENT
    , OBJECT_ID_CLASS BIGINT NOT NULL
    , OBJECT_ID_IDENTITY BIGINT NOT NULL
    , PARENT_OBJECT BIGINT
    , OWNER_SID BIGINT
    , ENTRIES_INHERITING BOOLEAN NOT NULL
    , PRIMARY KEY (ID)
    , UNIQUE UNIQUE_UK_3 (OBJECT_ID_CLASS,OBJECT_ID_IDENTITY)
    , FOREIGN KEY (PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY(ID)
	, FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES ACL_CLASS(ID)
	, FOREIGN KEY (OWNER_SID) REFERENCES ACL_SID(ID)
);

CREATE TABLE ACL_ENTRY(
    ID BIGINT NOT NULL AUTO_INCREMENT
    , ACL_OBJECT_IDENTITY BIGINT NOT NULL
    , ACE_ORDER INT NOT NULL
    , SID BIGINT NOT NULL
    , MASK INT NOT NULL
    , GRANTING BOOLEAN NOT NULL
    , AUDIT_SUCCESS BOOLEAN NOT NULL
    , AUDIT_FAILURE BOOLEAN NOT NULL
    , PRIMARY KEY (ID)
    , UNIQUE UNIQUE_UK_4 (ACL_OBJECT_IDENTITY,ACE_ORDER)
	, FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY(ID)
	, FOREIGN KEY (SID) REFERENCES ACL_SID(ID)
);


CREATE TABLE ADMIN_POST (
  ID BIGINT NOT NULL AUTO_INCREMENT
  , DATE DATETIME NOT NULL
  , MESSAGE VARCHAR(255) NOT NULL
  , PRIMARY KEY (ID)
);

CREATE TABLE PERSONAL_POST (
  ID BIGINT NOT NULL AUTO_INCREMENT
  , DATE DATETIME NOT NULL
  , MESSAGE VARCHAR(255) NOT NULL
  , PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC_POST (
  ID BIGINT NOT NULL AUTO_INCREMENT
  , DATE DATETIME NOT NULL
  , MESSAGE VARCHAR(255) NOT NULL
  , PRIMARY KEY (ID)
);
